import './home.scss';

export default function Home() {
  return (
    <main>
      <div>lorem</div>
      <div>lorem</div>
      <div>lorem</div>
      <div>lorem</div>
      <div>lorem</div>
      <div>lorem</div>
      <div>lorem</div>
      <div>lorem</div>
      <div>lorem</div>
      <div>lorem</div>
      <div>lorem</div>
      <div>lorem</div>
      <div>lorem</div>
      <div>lorem</div>
      <div>lorem</div>
      <div>lorem</div>
      <div>lorem</div>
      <div>lorem</div>
      <div>lorem</div>
      <div>lorem</div>
      <div>lorem</div>
      <div>lorem</div>
      <div>lorem</div>
      <div>lorem</div>
      <div>lorem</div>
      <div>lorem</div>
      <div>lorem</div>
      <div>lorem</div>
      <div>lorem</div>
      <div>lorem</div>
      <div>lorem</div>
      <div>lorem</div>
      <div>lorem</div>
      <div>lorem</div>
      <div>lorem</div>
      <div>lorem</div>
      <div>lorem</div>
      <div>lorem</div>
      <div>lorem</div>
      <div>lorem</div>
      <div>lorem</div>
      <div>lorem</div>
      <div>lorem</div>
      <div>lorem</div>
      <div>lorem</div>
      <div>lorem</div>
      <div>lorem</div>
      <div>lorem</div>
      <div>lorem</div>
      <div>lorem</div>
      <div>lorem</div>
      <div>lorem</div>
      <div>lorem</div>
      <div>lorem</div>
    </main>
  )
}
